In [1]:
import pandas as pd
import math

# TO FIND THE Flights that have been cancelled between start_date = '2021-09-01' and end_date = '2021-09-30'

In [2]:
df = pd.read_csv('Dataset/Combined_Flights_2021.csv')
df

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2021-03-03,SkyWest Airlines Inc.,SGU,PHX,False,False,724,714.0,0.0,-10.0,...,724.0,813.0,5.0,843,-25.0,0.0,-2.0,0800-0859,2,0.0
1,2021-03-03,SkyWest Airlines Inc.,PHX,SGU,False,False,922,917.0,0.0,-5.0,...,940.0,1028.0,3.0,1040,-9.0,0.0,-1.0,1000-1059,2,0.0
2,2021-03-03,SkyWest Airlines Inc.,MHT,ORD,False,False,1330,1321.0,0.0,-9.0,...,1336.0,1445.0,16.0,1530,-29.0,0.0,-2.0,1500-1559,4,0.0
3,2021-03-03,SkyWest Airlines Inc.,DFW,TRI,False,False,1645,1636.0,0.0,-9.0,...,1703.0,1955.0,7.0,2010,-8.0,0.0,-1.0,2000-2059,4,0.0
4,2021-03-03,SkyWest Airlines Inc.,PHX,BFL,False,False,1844,1838.0,0.0,-6.0,...,1851.0,1900.0,3.0,1925,-22.0,0.0,-2.0,1900-1959,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6311866,2021-06-01,Southwest Airlines Co.,BNA,MDW,False,False,1255,1301.0,6.0,6.0,...,1310.0,1416.0,5.0,1430,-9.0,0.0,-1.0,1400-1459,2,0.0
6311867,2021-06-01,Southwest Airlines Co.,BNA,MDW,False,False,730,727.0,0.0,-3.0,...,740.0,842.0,3.0,900,-15.0,0.0,-1.0,0900-0959,2,0.0
6311868,2021-06-01,Southwest Airlines Co.,BNA,MIA,False,False,800,757.0,0.0,-3.0,...,811.0,1056.0,5.0,1110,-9.0,0.0,-1.0,1100-1159,4,0.0
6311869,2021-06-01,Southwest Airlines Co.,BNA,MIA,False,False,1300,1252.0,0.0,-8.0,...,1300.0,1554.0,5.0,1620,-21.0,0.0,-2.0,1600-1659,4,0.0
6311870,2021-06-01,Southwest Airlines Co.,BNA,MKE,False,False,1925,1948.0,23.0,23.0,...,2000.0,2111.0,5.0,2055,21.0,1.0,1.0,2000-2059,2,0.0

In [3]:
start_date = '2021-09-01'
end_date = '2021-09-30'
# Select rows only for September month
mask = (df['FlightDate'] >= start_date) & (df['FlightDate'] <= end_date)
df2 = df.loc[mask]
print(df2)

         FlightDate               Airline Origin Dest  Cancelled  Diverted  \
2097993  2021-09-15  Delta Air Lines Inc.    MSP  SAT      False     False
2097994  2021-09-15  Delta Air Lines Inc.    CLE  ATL      False     False
2097995  2021-09-15  Delta Air Lines Inc.    JFK  MIA      False     False
2097996  2021-09-15  Delta Air Lines Inc.    ATL  IAD      False     False
2097997  2021-09-15  Delta Air Lines Inc.    SLC  GEG      False     False
...             ...                   ...    ...  ...        ...       ...
2665904  2021-09-29     Republic Airlines    EWR  RDU      False     False
2665905  2021-09-30     Republic Airlines    ORD  IND      False     False
2665906  2021-09-10     Republic Airlines    IAD  ROC      False      True
2665907  2021-09-23     Republic Airlines    EYW  EWR      False     False
2665908  2021-09-23     Republic Airlines    IAD  HHH      False      True

         CRSDepTime  DepTime  DepDelayMinutes  DepDelay  ...  WheelsOff  \
2097993        1945   1940.0              0.0      -5.0  ...     1956.0
2097994         700    657.0              0.0      -3.0  ...      714.0
2097995         730    725.0              0.0      -5.0  ...      740.0
2097996        1359   1356.0              0.0      -3.0  ...     1407.0
2097997        2259   2256.0              0.0      -3.0  ...     2307.0
...             ...      ...              ...       ...  ...        ...
2665904         820    859.0             39.0      39.0  ...      921.0
2665905        1600   1643.0             43.0      43.0  ...     1700.0
2665906        2235   2233.0              0.0      -2.0  ...     2301.0
2665907        1415   1249.0           1354.0    1354.0  ...     1308.0
2665908        1115   1252.0             97.0      97.0  ...     1302.0

         WheelsOn  TaxiIn  CRSArrTime  ArrDelay  ArrDel15  ArrivalDelayGroups  \
2097993    2217.0     8.0        2233      -8.0       0.0                -1.0
2097994     836.0    10.0         845       1.0       0.0                 0.0
2097995     959.0     6.0        1027     -22.0       0.0                -2.0
2097996    1526.0     6.0        1538      -6.0       0.0                -1.0
2097997    2326.0     4.0        2337      -7.0       0.0                -1.0
...           ...     ...         ...       ...       ...                 ...
2665904    1030.0     7.0        1003      34.0       1.0                 2.0
2665905    1832.0     5.0        1807      30.0       1.0                 2.0
2665906     234.0    14.0        2350       NaN       NaN                 NaN
2665907    1548.0     6.0        1725    1349.0       1.0                12.0
2665908    1105.0     5.0        1303       NaN       NaN                 NaN

         ArrTimeBlk  DistanceGroup  DivAirportLandings
2097993   2200-2259              5                 0.0
2097994   0800-0859              3                 0.0
2097995   1000-1059              5                 0.0
2097996   1500-1559              3                 0.0
2097997   2300-2359              3                 0.0
...             ...            ...                 ...
2665904   1000-1059              2                 0.0
2665905   1800-1859              1                 0.0
2665906   2300-2359              2                 1.0
2665907   1700-1759              5                 0.0
2665908   1300-1359              2                 1.0

[567916 rows x 61 columns]

In [7]:
df2 = df2.loc[(df2['Cancelled'] == True)]
df2

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2110239,2021-09-04,Delta Air Lines Inc.,MSY,ATL,True,False,545,NaN,NaN,NaN,...,NaN,NaN,NaN,815,NaN,NaN,NaN,0800-0859,2,0.0
2110398,2021-09-04,Delta Air Lines Inc.,MSP,MSY,True,False,1054,NaN,NaN,NaN,...,NaN,NaN,NaN,1332,NaN,NaN,NaN,1300-1359,5,0.0
2110399,2021-09-04,Delta Air Lines Inc.,MSY,MSP,True,False,1433,NaN,NaN,NaN,...,NaN,NaN,NaN,1725,NaN,NaN,NaN,1700-1759,5,0.0
2110414,2021-09-04,Delta Air Lines Inc.,MSY,ATL,True,False,700,NaN,NaN,NaN,...,NaN,NaN,NaN,930,NaN,NaN,NaN,0900-0959,2,0.0
2110592,2021-09-04,Delta Air Lines Inc.,MSY,DTW,True,False,600,NaN,NaN,NaN,...,NaN,NaN,NaN,930,NaN,NaN,NaN,0900-0959,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2664161,2021-09-24,Republic Airlines,SAV,EWR,True,False,715,NaN,NaN,NaN,...,NaN,NaN,NaN,926,NaN,NaN,NaN,0900-0959,3,0.0
2664174,2021-09-24,Republic Airlines,SRQ,EWR,True,False,1445,NaN,NaN,NaN,...,NaN,NaN,NaN,1733,NaN,NaN,NaN,1700-1759,5,0.0
2665860,2021-09-07,Republic Airlines,ORD,BOS,True,False,1535,1559.0,24.0,24.0,...,NaN,NaN,NaN,1907,NaN,NaN,NaN,1900-1959,4,0.0
2665861,2021-09-07,Republic Airlines,ORD,BWI,True,False,1400,1354.0,0.0,-6.0,...,NaN,NaN,NaN,1702,NaN,NaN,NaN,1700-1759,3,0.0
2665890,2021-09-23,Republic Airlines,CHS,EWR,True,False,1125,1121.0,0.0,-4.0,...,NaN,NaN,NaN,1323,NaN,NaN,NaN,1300-1359,3,0.0

In [8]:
pd.DataFrame(df2['Airline'].value_counts()).head(1)

                        count
Airline
Southwest Airlines Co.   2326